version: '3.1'

services:
    aoweb:
        image: "aoweb"
        ports:
            - "8080:8080"
        depends_on:
            - PostgresSQL

        environment:
            - spring.main.banner-mode=off
            - spring.output.ansi.enabled=ALWAYS
            - logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss}){blue} %clr(%-5p) %clr(%logger{0}){blue} %clr(%m){green}%n
            - jwt.secret.key=g8954g++46i984*-76i89*43-+2458+-23r4w-e65f1w+-e98fsdf+-9we-*/
            - jwt.expiration.time.token.seconds=86400
            - jwt.authorizeRequests.patterns.auth=/api/v1/auth/**
            - jwt.authorizeRequests.patterns.classes=/api/v1/classes/**
            - spring.main.allow-circular-references=true
            - spring.datasource.driverClassName=org.postgresql.Driver
            - spring.datasource.url=jdbc:postgresql://db:5432/aoweb
            - spring.datasource.username=postgres
            - spring.datasource.password=root
            - spring.jpa.show-sql=true
            - spring.jpa.hibernate.ddl-auto=update

        networks:
            - ao
    db:
        image: postgres:latest
        container_name: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        networks:
            - ao

networks:
    ao:

