version: '3.1'
services:
    aoweb:
        image: "aoweb.jar"
        ports:
            - "8080:8080"
        depends_on:
            - PostgresSQL

        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgresSQL:5432/aoweb
            - SPRING_DATASOURCE_USERNAME=postgres
            - SPRING_DATASOURCE_PASSWORD=password
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    PostgresSQL:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=root
            - POSTGRES_USER=postgres
            - POSTGRES_DB=aoweb
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
