version: '3.1'

services:
    app:
        container_name: aoweb
        image: 'aoweb-backend:latest'
        ports:
            - '8080:8000'
        depends_on:
            - db
        environment:
            - JWT_SECRET_KEY=g8954g++46i984*-76i89*43-+2458+-23r4w-e65f1w+-e98fsdf+-9we-*/
            - JWT_ACCESS_TOKEN_EXPIRES=86400
            - JWT_AUTHORIZE_PATH=/api/v1/auth/**
            - JWT_AUTHORIZE_PATH=/api/v1/classes/**

    db:
        container_name: postgres
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=aoweb
        volumes:
            - ./scripts:/docker-entrypoint-initdb.d postgres
        restart: unless-stopped